services:

  # PostgreSQL
  # https://github.com/postgres/postgres
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=pp
      - POSTGRES_USER=pp
      - POSTGRES_PASSWORD=pp
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "pp", "-U", "pp" ]
      timeout: 45s
      interval: 10s
      retries: 50
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # PGWeb
  # https://github.com/sosedoff/pgweb
  # https://hub.docker.com/r/sosedoff/pgweb
  postgres-web:
    depends_on:
      - postgres
    image: sosedoff/pgweb:0.15.0
    environment:
      - "PGWEB_DATABASE_URL=postgres://pp:pp@postgres:5432?sslmode=disable"
    ports:
      - 5433:8081
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
